services:
  - type: web
    name: atlvs-taskflow
    env: php
    plan: free
    buildCommand: ./render-build.sh
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: NODE_VERSION
        value: 18.16.0
      - key: PHP_VERSION
        value: 8.2.0
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
